// <auto-generated />
using System;
using EscolhaRestaurante.Infratructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscolhaRestaurante.Infratructure.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    partial class RestauranteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EscolhaRestaurante.ApplicationCore.Entities.Restaurante", b =>
                {
                    b.Property<int>("RestauranteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UltimaEscolha")
                        .HasColumnType("DateTime");

                    b.HasKey("RestauranteID");

                    b.ToTable("Restaurante");
                });

            modelBuilder.Entity("EscolhaRestaurante.ApplicationCore.Entities.Voto", b =>
                {
                    b.Property<int>("VotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("DateTime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RestauranteID")
                        .HasColumnType("int");

                    b.HasKey("VotoID");

                    b.HasIndex("RestauranteID");

                    b.ToTable("Voto");
                });

            modelBuilder.Entity("EscolhaRestaurante.ApplicationCore.Entities.Voto", b =>
                {
                    b.HasOne("EscolhaRestaurante.ApplicationCore.Entities.Restaurante", "Restaurante")
                        .WithMany("Votos")
                        .HasForeignKey("RestauranteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
