// <auto-generated />
using System;
using EscolhaRestaurante.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscolhaRestaurante.Migrations
{
    [DbContext(typeof(EscolhaRestauranteDbContext))]
    [Migration("20191006144848_UltimaEscolha")]
    partial class UltimaEscolha
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EscolhaRestaurante.Models.Restaurante", b =>
                {
                    b.Property<int>("RestauranteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaEscolha")
                        .HasColumnType("datetime2");

                    b.HasKey("RestauranteID");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("EscolhaRestaurante.Models.Voto", b =>
                {
                    b.Property<int>("VotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RestauranteID")
                        .HasColumnType("int");

                    b.HasKey("VotoID");

                    b.HasIndex("RestauranteID");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("EscolhaRestaurante.Models.Voto", b =>
                {
                    b.HasOne("EscolhaRestaurante.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteID");
                });
#pragma warning restore 612, 618
        }
    }
}
